export const portfolioAgentAbi = [
  {
    name: "registerPortfolio",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "risk",     type: "uint8"  },
      { name: "ethBps_",  type: "uint16" },
      { name: "wbtcBps_", type: "uint16" },
      { name: "usdcBps_", type: "uint16" },
    ],
    outputs: [],
  },
  {
    name: "depositFeesForCaller",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "lockDurationBlocks", type: "uint256" }],
    outputs: [],
  },
  {
    name: "startAutomation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "frequencyBlocks", type: "uint32"  },
      { name: "numCalls",        type: "uint32"  },
      { name: "gasLimit",        type: "uint32"  },
      { name: "maxFeePerGas",    type: "uint256" },
      { name: "schedulerTtl",   type: "uint32"  },
    ],
    outputs: [],
  },
  {
    name: "cancelAutomation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "withdrawFees",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    name: "ritualBalance",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "contractRitualBalance",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "portfolios",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "registered",  type: "bool"    },
      { name: "riskMode",    type: "uint8"   },
      { name: "ethBps",      type: "uint16"  },
      { name: "wbtcBps",     type: "uint16"  },
      { name: "usdcBps",     type: "uint16"  },
      { name: "executor",    type: "address" },
      { name: "scheduleId",  type: "uint256" },
    ],
  },
  {
    name: "pendingJobId",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bytes32" }],
  },
  {
    name: "lastCycleId",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "TickFailed",
    inputs: [
      { name: "owner",   type: "address", indexed: true  },
      { name: "tickIdx", type: "uint256", indexed: true  },
      { name: "phase",   type: "string",  indexed: false },
      { name: "reason",  type: "string",  indexed: false },
    ],
  },
  {
    type: "event",
    name: "AutomationScheduled",
    inputs: [
      { name: "owner",     type: "address", indexed: true  },
      { name: "callId",    type: "uint256", indexed: true  },
      { name: "frequency", type: "uint32",  indexed: false },
      { name: "numCalls",  type: "uint32",  indexed: false },
    ],
  },
  {
    type: "event",
    name: "AutomationCancelled",
    inputs: [
      { name: "owner",  type: "address", indexed: true },
      { name: "callId", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AutomationTriggered",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "jobId", type: "bytes32", indexed: true },
    ],
  },
  {
    type: "event",
    name: "SovereignAgentResult",
    inputs: [
      { name: "owner",        type: "address", indexed: true  },
      { name: "jobId",        type: "bytes32", indexed: true  },
      { name: "cycleId",      type: "uint256", indexed: false },
      { name: "hasError",     type: "bool",    indexed: false },
      { name: "textResponse", type: "string",  indexed: false },
      { name: "errorMessage", type: "string",  indexed: false },
    ],
  },
] as const;
