export const portfolioAgentAbi = [
  {
    name: "registerPortfolio",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "risk", type: "uint8" },
      { name: "ethBps_", type: "uint16" },
      { name: "wbtcBps_", type: "uint16" },
      { name: "usdcBps_", type: "uint16" },
      { name: "executor", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "depositFeesForCaller",
    type: "function",
    stateMutability: "payable",
    inputs: [{ name: "lockDurationBlocks", type: "uint256" }],
    outputs: [],
  },
  {
    name: "startAutomation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "frequencyBlocks", type: "uint32" },
      { name: "numCycles", type: "uint32" },
      { name: "gasLimit", type: "uint32" },
      { name: "maxFeePerGas", type: "uint256" },
      { name: "schedulerTtl", type: "uint32" },
    ],
    outputs: [],
  },
  {
    name: "cancelAutomation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "lastPricesBody",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "bytes" }],
  },
  {
    name: "ritualBalance",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "portfolios",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "registered", type: "bool" },
      { name: "riskMode", type: "uint8" },
      { name: "ethBps", type: "uint16" },
      { name: "wbtcBps", type: "uint16" },
      { name: "usdcBps", type: "uint16" },
      { name: "executor", type: "address" },
      { name: "scheduleId", type: "uint256" },
    ],
  },
  {
    name: "lastCycleId",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "COINGECKO_URL",
    type: "function",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    name: "MODEL",
    type: "function",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "event",
    name: "RebalanceDecision",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "cycleId", type: "uint256", indexed: true },
      { name: "executionIndex", type: "uint256", indexed: true },
      { name: "llmHasError", type: "bool", indexed: false },
      { name: "completionPayload", type: "bytes", indexed: false },
      { name: "errorMessage", type: "string", indexed: false },
      { name: "pricesHash", type: "bytes32", indexed: false },
      { name: "riskMode", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PricesSnapshot",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "executionIndex", type: "uint256", indexed: true },
      { name: "cycleId", type: "uint256", indexed: true },
      { name: "statusCode", type: "uint16", indexed: false },
      { name: "body", type: "bytes", indexed: false },
    ],
  },
] as const;
